projects:
  database:
    schemaPath: src/generated/prisma.graphql
    extensions:
      prisma: database/prisma/prisma.yml
  authorizationApi:
    schemaPath: database/authorizationApi/schema.graphql
    extensions:
      endpoints:
        default: http://lolcahost:5000
  licenceApi:
    schemaPath: database/licenceApi/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:5010


# projects:
#   database:
#     schemaPath: src/generated/prisma.graphql
#     extensions:
#       prisma: database/prisma/prisma.yml
#       codegen:
#         -  generator: prisma-binding
#            language: javascript
#            output:
#             binding: src/generated/prisma.js
#   authorizationApi:
#     schemaPath: src/generated/authorizationApi.graphql
#     extensions:
#       prisma: database/authorizationApi/prisma.yml
#       codegen:
#         - generator: prisma-binding
#           language: javascript
#           output:
#             binding: src/generated/authorizationApi.js